tif baseline argo-cc argo-ci

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -127,72 +127,72 @@ jobs:
         if: steps.check_namespace.outputs.exists == 'false'
         run: | 
           kubectl create namespace argocd
-          kubectl create namespace services
+         
 
       - name: Install Argo CD
         if: steps.check_namespace.outputs.exists == 'false'
         run: |
           kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
 
-  configure-argo:
-    needs: [deploy-infra, install-argo]  # configure-argo depends on deploy-infra and optionally on install-argo
-    if: contains(github.event.head_commit.message, 'argo-cc') || contains(github.event.head_commit.message, 'argo-ci')
-    runs-on: ubuntu-latest
-    steps:    
-      - name: Checkout code
-        uses: actions/checkout@v4.1.6
-      - name: Setup Google Cloud
-        uses: ./.github/actions/gcloud-credentials
-        with:
-          credentials_json: ${{ secrets.GPC_CREDENTIALS_FILE }}
-      - name: Install gke-gcloud-auth-plugin
-        run: gcloud components install gke-gcloud-auth-plugin
+  # configure-argo:
+  #   needs: [deploy-infra, install-argo]  # configure-argo depends on deploy-infra and optionally on install-argo
+  #   if: contains(github.event.head_commit.message, 'argo-cc') || contains(github.event.head_commit.message, 'argo-ci')
+  #   runs-on: ubuntu-latest
+  #   steps:    
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4.1.6
+  #     - name: Setup Google Cloud
+  #       uses: ./.github/actions/gcloud-credentials
+  #       with:
+  #         credentials_json: ${{ secrets.GPC_CREDENTIALS_FILE }}
+  #     - name: Install gke-gcloud-auth-plugin
+  #       run: gcloud components install gke-gcloud-auth-plugin
         
-      - name: Get Kubernetes Credentials
-        run: |
-          gcloud container clusters get-credentials primary --zone "us-east1-b" --project ${{ secrets.PROJECT_ID }}
+  #     - name: Get Kubernetes Credentials
+  #       run: |
+  #         gcloud container clusters get-credentials primary --zone "us-east1-b" --project ${{ secrets.PROJECT_ID }}
       
-      - name: Create Cloudflare API Token Secret
-        env:
-          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
-          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
-        run: |
-          kubectl create namespace services-cert-manager || echo " namespace services-cert-manager already exists"
-          kubectl create secret generic cloudflare-token-secret \
-            --from-literal=cloudflare-token=$CLOUDFLARE_TOKEN \
-            --from-literal=zone-id=$CLOUDFLARE_ZONE_ID \
-            --namespace services-cert-manager || echo " secret already exists" 
-          kubectl create namespace services-traefik
-          kubectl create role service-viewer --verb=get,list --resource=services -n services-traefik && kubectl create rolebinding service-viewer-binding --role=service-viewer --serviceaccount=services-cert-manager:default -n services-traefik
+  #     - name: Create Cloudflare API Token Secret
+  #       env:
+  #         CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
+  #         CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
+  #       run: |
+  #         kubectl create namespace services-cert-manager || echo " namespace services-cert-manager already exists"
+  #         kubectl create secret generic cloudflare-token-secret \
+  #           --from-literal=cloudflare-token=$CLOUDFLARE_TOKEN \
+  #           --from-literal=zone-id=$CLOUDFLARE_ZONE_ID \
+  #           --namespace services-cert-manager || echo " secret already exists" 
+  #         kubectl create namespace services-traefik
+  #         kubectl create role service-viewer --verb=get,list --resource=services -n services-traefik && kubectl create rolebinding service-viewer-binding --role=service-viewer --serviceaccount=services-cert-manager:default -n services-traefik
 
-      - name: Install Argo CD CLI
-        run: |
-          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
-          chmod +x /usr/local/bin/argocd
+  #     - name: Install Argo CD CLI
+  #       run: |
+  #         curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+  #         chmod +x /usr/local/bin/argocd
       
-      - name: Start Port Forwarding
-        run: |
-          kubectl wait --for=condition=available --timeout=120s deploy/argocd-server -n argocd
-          kubectl port-forward svc/argocd-server -n argocd 8080:443 &
-          sleep 10  # Gives additional time for the port forwarding to establish
-        shell: bash
-      - name: Retrieve Argo CD API server password
-        run: |          
-          ARGOCD_PWD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
-          echo "ARGOCD_PWD=$ARGOCD_PWD" >> $GITHUB_ENV
+  #     - name: Start Port Forwarding
+  #       run: |
+  #         kubectl wait --for=condition=available --timeout=120s deploy/argocd-server -n argocd
+  #         kubectl port-forward svc/argocd-server -n argocd 8080:443 &
+  #         sleep 10  # Gives additional time for the port forwarding to establish
+  #       shell: bash
+  #     - name: Retrieve Argo CD API server password
+  #       run: |          
+  #         ARGOCD_PWD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
+  #         echo "ARGOCD_PWD=$ARGOCD_PWD" >> $GITHUB_ENV
 
-      - name: Login to Argo CD
-        run: echo y | argocd login localhost:8080 --username admin --password $ARGOCD_PWD --insecure
-        env:
-          ARGOCD_PWD: ${{ env.ARGOCD_PWD }}
+  #     - name: Login to Argo CD
+  #       run: echo y | argocd login localhost:8080 --username admin --password $ARGOCD_PWD --insecure
+  #       env:
+  #         ARGOCD_PWD: ${{ env.ARGOCD_PWD }}
   
-      - name: Create Root Application
-        run: |
-          kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/01-infra-services-appproject.yaml
-          kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/03-infra-application.yaml
-          kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/02-app-services-appproject.yaml
-          kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/04-app-application.yaml
+  #     - name: Create Root Application
+  #       run: |
+  #         kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/01-infra-services-appproject.yaml
+  #         kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/03-infra-application.yaml
+  #         kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/02-app-services-appproject.yaml
+  #         kubectl apply -f SD2024/tif/cloud-shared-services/argocd/root-project/04-app-application.yaml
 
-      - name: Cleanup Port Forwarding
-        if: always()
-        run: killall kubectl
+  #     - name: Cleanup Port Forwarding
+  #       if: always()
+  #       run: killall kubectl
